shell.run("wget https://github.com/Egyember/CCtweaked-Network/raw/reactor_controller/src/base.lua")
shell.run("wget https://github.com/Egyember/CCtweaked-Network/raw/reactor_controller/src/stack.lua")
shell.run("wget https://github.com/Egyember/CCtweaked-Network/raw/reactor_controller/src/startup.lua")
shell.run("wget https://github.com/Egyember/CCtweaked-Network/raw/reactor_controller/src/do/putInFuel.lua")
fs.makeDir("/do")
shell.run("mv putInFuel.lua /do/putInFuel.lua")
