shell.run("wget https://github.com/Egyember/CCtweaked-Network/raw/master/src/base.lua")
shell.run("wget https://github.com/Egyember/CCtweaked-Network/raw/master/src/stack.lua")
shell.run("wget https://github.com/Egyember/CCtweaked-Network/raw/master/src/startup.lua")
shell.run("wget https://github.com/Egyember/CCtweaked-Network/raw/master/src/globalVariable.lua")
fs.makeDir("/do")
